param([switch]$StartOnLaunch)
$ErrorActionPreference='Stop';Add-Type -AssemblyName System.Windows.Forms;Add-Type -AssemblyName System.Drawing
$createdNew=$false;$script:assistMutex=New-Object Threading.Mutex($true,'Local\TubeTVAssistUI',[ref]$createdNew);if(-not $createdNew){exit}
$root=Split-Path -Parent $MyInvocation.MyCommand.Path;$project=Split-Path -Parent $root;$private=Join-Path $root 'private';$configPath=Join-Path $private 'worker-config.json';$pidPath=Join-Path $private 'worker.pid';New-Item -ItemType Directory -Force -Path $private|Out-Null
if(-not(Test-Path -LiteralPath $configPath)){$bytes=New-Object byte[] 48;$rng=[Security.Cryptography.RandomNumberGenerator]::Create();try{$rng.GetBytes($bytes)}finally{$rng.Dispose()};$secret=($bytes|ForEach-Object{$_.ToString('x2')})-join'';[IO.File]::WriteAllText($configPath,(@{secret=$secret;port=8788;maxJobs=2}|ConvertTo-Json),[Text.UTF8Encoding]::new($false))}
$config=Get-Content -Raw -LiteralPath $configPath|ConvertFrom-Json;$node=(Get-Command node.exe -ErrorAction Stop).Source;$ffmpeg=(Get-Command ffmpeg.exe -ErrorAction Stop).Source;$tailscale='C:\Program Files\Tailscale\tailscale.exe';$ssh='C:\Windows\System32\OpenSSH\ssh.exe';$key=Join-Path $project '.tubetv-local\tubetv_host_ed25519';$known=Join-Path $project '.tubetv-local\known_hosts'
function Get-WorkerProcess{if(-not(Test-Path -LiteralPath $pidPath)){return $null};$workerPid=[int](Get-Content -LiteralPath $pidPath -ErrorAction SilentlyContinue);return Get-Process -Id $workerPid -ErrorAction SilentlyContinue}
function Start-Worker{if(Get-WorkerProcess){return};$env:TUBETV_WORKER_SECRET=[string]$config.secret;$env:TUBETV_WORKER_PORT=[string]$config.port;$env:TUBETV_WORKER_MAX_JOBS=[string]$config.maxJobs;$env:TUBETV_WORKER_FFMPEG=$ffmpeg;$out=Join-Path $private 'worker-out.log';$err=Join-Path $private 'worker-error.log';$process=Start-Process -FilePath $node -ArgumentList @((Join-Path $root 'worker.js')) -WorkingDirectory $root -WindowStyle Hidden -PassThru -RedirectStandardOutput $out -RedirectStandardError $err;$process.Id|Set-Content -LiteralPath $pidPath -Encoding ASCII;if(Test-Path -LiteralPath $tailscale){& $tailscale serve --bg --yes --https=8443 "http://127.0.0.1:$($config.port)"|Out-Null}}
function Stop-Worker{$process=Get-WorkerProcess;if($process){Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue};Remove-Item -LiteralPath $pidPath -Force -ErrorAction SilentlyContinue}
function Set-LaptopMode([string]$mode){if(-not(Test-Path -LiteralPath $key)){throw 'Chiave SSH TubeTV non trovata.'};& $ssh -i $key -o "UserKnownHostsFile=$known" tubetv@192.168.1.110 "sudo /usr/local/sbin/tubetv-mode $mode"|Out-Null;if($LASTEXITCODE-ne 0){throw 'Il portatile non ha accettato il cambio modalità.'}}
$form=New-Object Windows.Forms.Form;$form.Text='TubeTV Assist';$form.Size=New-Object Drawing.Size(520,420);$form.StartPosition='CenterScreen';$form.BackColor=[Drawing.Color]::FromArgb(12,13,18);$form.ForeColor=[Drawing.Color]::White;$form.Font=New-Object Drawing.Font('Segoe UI',10)
$title=New-Object Windows.Forms.Label;$title.Text='TUBE TV  ·  DESKTOP ASSIST';$title.Font=New-Object Drawing.Font('Segoe UI',18,[Drawing.FontStyle]::Bold);$title.ForeColor=[Drawing.Color]::FromArgb(230,57,70);$title.AutoSize=$true;$title.Location=New-Object Drawing.Point(28,25);$form.Controls.Add($title)
$subtitle=New-Object Windows.Forms.Label;$subtitle.Text='RTX 3080 · conversione GPU opzionale';$subtitle.AutoSize=$true;$subtitle.ForeColor=[Drawing.Color]::FromArgb(150,155,170);$subtitle.Location=New-Object Drawing.Point(31,67);$form.Controls.Add($subtitle)
$status=New-Object Windows.Forms.Label;$status.Size=New-Object Drawing.Size(440,45);$status.Location=New-Object Drawing.Point(32,112);$status.TextAlign='MiddleCenter';$status.Font=New-Object Drawing.Font('Segoe UI',14,[Drawing.FontStyle]::Bold);$form.Controls.Add($status)
$toggle=New-Object Windows.Forms.Button;$toggle.Size=New-Object Drawing.Size(440,65);$toggle.Location=New-Object Drawing.Point(32,165);$toggle.FlatStyle='Flat';$toggle.Font=New-Object Drawing.Font('Segoe UI',15,[Drawing.FontStyle]::Bold);$form.Controls.Add($toggle)
$label=New-Object Windows.Forms.Label;$label.Text='Potenza del portatile';$label.AutoSize=$true;$label.ForeColor=[Drawing.Color]::FromArgb(150,155,170);$label.Location=New-Object Drawing.Point(32,252);$form.Controls.Add($label)
$eco=New-Object Windows.Forms.Button;$normal=New-Object Windows.Forms.Button;$boost=New-Object Windows.Forms.Button;$buttons=@($eco,$normal,$boost);$names=@('ECO','NORMALE','BOOST');for($i=0;$i-lt 3;$i++){$buttons[$i].Text=$names[$i];$buttons[$i].Size=New-Object Drawing.Size(138,46);$buttons[$i].Location=New-Object Drawing.Point((32+$i*151),282);$buttons[$i].FlatStyle='Flat';$buttons[$i].ForeColor=[Drawing.Color]::White;$buttons[$i].BackColor=[Drawing.Color]::FromArgb(30,32,42);$form.Controls.Add($buttons[$i])}
$note=New-Object Windows.Forms.Label;$note.Text='OFF: il fisso non usa CPU. TubeTV continua sul portatile.';$note.AutoSize=$true;$note.ForeColor=[Drawing.Color]::FromArgb(120,126,142);$note.Location=New-Object Drawing.Point(32,350);$form.Controls.Add($note)
function Refresh-Ui{$on=[bool](Get-WorkerProcess);$status.Text=if($on){'ASSISTENZA ATTIVA'}else{'ASSISTENZA SPENTA'};$status.ForeColor=if($on){[Drawing.Color]::FromArgb(57,220,142)}else{[Drawing.Color]::FromArgb(160,166,180)};$toggle.Text=if($on){'SPEGNI ASSISTENZA DEL FISSO'}else{'ACCENDI ASSISTENZA DEL FISSO'};$toggle.BackColor=if($on){[Drawing.Color]::FromArgb(37,112,78)}else{[Drawing.Color]::FromArgb(173,37,49)}}
$toggle.Add_Click({try{if(Get-WorkerProcess){Stop-Worker}else{Start-Worker};Start-Sleep -Milliseconds 500;Refresh-Ui}catch{[Windows.Forms.MessageBox]::Show($_.Exception.Message,'TubeTV Assist')|Out-Null}});$eco.Add_Click({try{Set-LaptopMode 'eco'}catch{[Windows.Forms.MessageBox]::Show($_.Exception.Message)|Out-Null}});$normal.Add_Click({try{Set-LaptopMode 'normal'}catch{[Windows.Forms.MessageBox]::Show($_.Exception.Message)|Out-Null}});$boost.Add_Click({try{Set-LaptopMode 'boost'}catch{[Windows.Forms.MessageBox]::Show($_.Exception.Message)|Out-Null}})
if($StartOnLaunch){Start-Worker};Refresh-Ui;[void]$form.ShowDialog()
