[PHP]
display_errors=Off
log_errors=On
memory_limit=1024M
max_execution_time=0
max_input_time=-1
output_buffering=Off
zlib.output_compression=Off
implicit_flush=Off
allow_url_fopen=On
default_socket_timeout=30
realpath_cache_size=8192K
realpath_cache_ttl=600
extension_dir="C:/Users/jonat/AppData/Local/Microsoft/WinGet/Packages/PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe/ext"
extension=curl
extension=openssl
extension=mbstring
curl.cainfo="C:/Users/jonat/Desktop/TVTUBE/.tubetv-local/desktop-host/app/cacert.pem"
openssl.cafile="C:/Users/jonat/Desktop/TVTUBE/.tubetv-local/desktop-host/app/cacert.pem"

[Date]
date.timezone=Europe/Zurich
